### ISSUE TITLE
Set default interpolants to log where appropriate

### ISSUE THREAD

**Issue by bfarr** [FarrOutLab/GWInferno#37]
In some cases (e.g., primary mass) constructing the interpolant in log-log space performs much better.  We should update those cases to use the appropriate interpolant by default.

**Comment by bruce-edelman** [comment]
For reference here's some of my thoughts on the choices for cyb paper:

I've found for modeling any probability distribution with the psplines you want the log-y basis and only don't want that if using the bsplines for some modulation. 

For the x bases we ended up only using log scales when the domain was primary mass and redshift. I think using the log scales for masses is well motivated however I am not sure if it actually is the best choice for redshift or jot

**Comment by bfarr** [comment]
This was resolved with #106.
